### PR TITLE
Fix shebang

### PR DESCRIPTION
**Pull request by sambrightman**

### CODE REVIEW

**Comment by rernst** [comment]
Please make a new pull request from and based on the develop branch. Although this fix is trivial I rather not directly develop on the master branch. I will merge this with the master branch when releasing a new version. Do you need this change asap?

**Comment by sambrightman** [comment]
My mistake, my local branch was still on master. Is there a problem setting the base to `CuppenResearch:develop`? As it stands the diff is still correct...

Not urgent.

**Comment by rernst** [comment]
When I changed the base branch to master it was cluttered with merge commits from develop to master (releases basically). Now it looks clean though, thanks and merged!

**Comment by sambrightman** [comment]
Great!

**Pull request merged**
